### ISSUE TITLE
Server crash with Roots 1.10.2-0.109.0

### ISSUE THREAD

**Issue by Renadarain** [elucent/Roots#86]
Hi,

MC: 1.10.2
Forge: forge-1.10.2-12.18.1.2017-installer 
          forge-1.10.2-12.18.1.2026-installer
Roots 1.10.2-0.109.0

Server crashes when Enhanced Server Moderation is installed. roots-1.10.2-0.109.0 was fine.
http://minecraft.curseforge.com/projects/enhanced-server-moderation?gameCategorySlug=mc-mods&projectID=224460

http://pastebin.com/hFwLbn82

Regards,
Renada

**Comment by elucent** [comment]
Fixed, will be in the next release.

**Comment by mrsmn** [comment]
Just to let you know that this still happens with roots-1.10.2-0.110.0.

Cheers.

**Comment by mrsmn** [comment]
@elucent Do you guys have an ETA for the next roots release? A lot of users can't update their modpacks if they want to use ESM.

Thank you.

**Comment by elucent** [comment]
We're a bit busy with The Modding Trials for now, but that will be over in a few days. We were hoping to get some of our new content completed before our next release, but I don't think we'll have it done as soon as you like. I'll disable it all and release something new soon.

**Comment by mrsmn** [comment]
Awesome, thank you. And thank you for Roots (I feel people don't thank modauthors enough).
